version: "3.8"

services:
  go-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: air
    environment:
      - AIR_WATCH=./